# conda env create --file environment.yml

name: sp500analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib=3.3.4
  - numpy=1.18.5
  - pandas=1.2.4
  - pip
  - plotly
  - python=3.8.13
  - scipy=1.6.2
  - seaborn=0.11
  - sklearn 
  - pip:
    - dcor